### ISSUE TITLE
bug: stats panel updates don't sync with edits in data modal

### ISSUE THREAD

**Issue by ericberlow** [ericberlow/openmappr#3]
open project. click on 'selection' button on the left to open 'selection' panel. click on the database button at the top of the selection panel ('edit data'). this opens a modal where you can edit attributes -  show/hide, re-order (drag and drop), change rendering type etc.    edit some attributes (change order, hide some, change render types.  then close modal. click on the 'stats' button to open the 'stats panel'.  the edits you made will not be visible.  refresh browser. now the edits are visible.    stats panel attribute rendering should sync with any edits that are made.

**Comment by ericberlow** [comment]
@mandeepm91 - you can test with this project http://openmappr.swall.org/projects/5b4f5cbddedeac0013545615

**Comment by mandeepm91** [comment]
@ericberlow  I have updated my changes on the server. Pls test and let me know if you find any issues.

**Comment by ericberlow** [comment]
@mandeepm91 - all seems to be working great.  any slowness in editing or moving attributes i think is no different than before.

**Comment by mandeepm91** [comment]
Thanks @ericberlow . I've merged the PR. Closing this issue now
