### ISSUE TITLE
move url from openmappr.swall.org  to openmappr.org

### ISSUE THREAD

**Issue by ericberlow** [ericberlow/openmappr#9]
@mandeepm91 - i realized that openmappr.org is available so i purchased the domain.  can you redirect our server to openmappr.org instead of openmappr.swall.org?  let me know if you need to get into the dreamhost panel https://panel.dreamhost.com/

**Comment by mandeepm91** [comment]
@ericberlow Done. Please check. It is possible you might face some DNS related issues initially but it should be fine in an hour or so. It's running fine for me now. 

As of now both openmappr.swall.org and openmappr.com are pointing to the same AWS instance. Do you want me to remove the linkage for openmappr.swall.org?

**Comment by mandeepm91** [comment]
@ericberlow I've made the necessary changes. Will check after a few hours. The openmappr.com was working fine on my laptop but not on my mobile. I have submitted a refresh request. Will check in a couple of hours and update

**Comment by mandeepm91** [comment]
Redirection is working fine but openmappr.org is still not pointing to the AWS instance. Will check again after a while

**Comment by ericberlow** [comment]
Interesting - seems like http://openmappr.swall.org is still working and pointing to AWS instance.

**Comment by mandeepm91** [comment]
http://www.openmappr.org/ is working fine for me. Is it working for you? Still http://openmappr.org is not working

**Comment by mandeepm91** [comment]
@ericberlow  It's all working for me now. openmappr.com redirecting to openmappr.org and both openmappr.org and wwww.openmappr.org pointing to our AWS EC2 instance. So, it seems we don't need to change anything in the DNS settings. Let me know once it starts working for you too

**Comment by ericberlow** [comment]
working for me now too!  thanks.  perfect.
